# Generated by Django 4.1 on 2022-11-06 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_end_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 16, 58, 0, 622067, tzinfo=datetime.timezone.utc)),
        ),
    ]
